name: Build App
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Build App
       run: |
            Scheme="Browser"
            XCProject="_Project/Browser.xcodeproj"
            xcodebuild -jobs $(sysctl -n hw.ncpu) -project "$XCProject" -scheme "$Scheme" -configuration Release -arch arm64 -sdk appletvos -derivedDataPath "$TMPDIR" CODE_SIGNING_ALLOWED=NO DSTROOT=$AppTMP/install ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
            cp "$(echo $TMPDIR/Build/Products/Release*/*.app)" .
            cp "$(echo *.app)/Browser" Browser
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Built App"
            git push
